-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.student
(
    id serial NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    birthday date,
    gender boolean,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subject
(
    id serial NOT NULL,
    name character varying NOT NULL,
    credit integer,
    optional boolean DEFAULT false,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.teacher
(
    id serial NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    degree character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.study_plan
(
    id serial NOT NULL,
    name character varying NOT NULL,
    vigence date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subject_plan
(
    id_subject integer,
    id_study_plan integer,
    semester smallint,
    id serial NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.course
(
    id_teacher integer,
    id_subject_plan integer,
    curricular_period date,
    id serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enrollment
(
    id_student integer,
    id_course integer,
    grade numeric(4, 2)
);

ALTER TABLE IF EXISTS public.subject_plan
    ADD CONSTRAINT fk_study_plan FOREIGN KEY (id_study_plan)
    REFERENCES public.study_plan (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subject_plan
    ADD FOREIGN KEY (id_subject)
    REFERENCES public.subject (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.course
    ADD CONSTRAINT fk_teacher FOREIGN KEY (id_teacher)
    REFERENCES public.teacher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.course
    ADD CONSTRAINT fk_subject_plan FOREIGN KEY (id_subject_plan)
    REFERENCES public.subject_plan (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT fk_student FOREIGN KEY (id_student)
    REFERENCES public.student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT fk_course FOREIGN KEY (id_course)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;